---
title: "part2"
output: html_document
date: "2026-05-14"
---

```{r setup, include=FALSE}
# This sets the directory for ALL subsequent chunks
knitr::opts_knit$set(root.dir = '/Users/marco/Desktop/SingleCells/part2')
```

```{r}
suppressPackageStartupMessages({
  library(Seurat)
  library(Matrix)
  library(patchwork)
  library(dplyr)
  library(ggplot2)
  library(pheatmap)
  library(SingleCellExperiment)
  #library(zellkonverter)
  #library(simspec)
})

options(Seurat.object.assay.version = "v3")
```

# Loading Seurat Obj (all 4 samples integrated together 2KO (MECOM-) and 2WT)
```{r}
seurat_int_all <- readRDS("seurat_int_all.rds")

#metadata
head(seurat_int_all@meta.data)

# Plot by Number
Idents(seurat_int_all) <- "seurat_clusters"

DimPlot(seurat_int_all, reduction = "umap", label = TRUE, repel = TRUE) + 
  ggtitle("Ordered by Numbers")

# Plot by Name
Idents(seurat_int_all) <- "final_type" 

DimPlot(seurat_int_all, reduction = "umap", label = FALSE) + 
  ggtitle("Ordered by Name")
```

# Analize composition WT vs KO
```{r}
DimPlot(seurat_int_all, reduction = "umap", group.by = "condition")

DimPlot(seurat_int_all, reduction = "umap", split.by = "condition")

# Use final_type to get biological names instead of numbers
counts <- table(seurat_int_all$final_type, seurat_int_all$condition)

# Convert to proportions
proportions <- as.data.frame(prop.table(counts, margin = 1))
colnames(proportions) <- c("CellType", "Condition", "Proportion")

# Plot - note that X is now 'CellType' which contains the strings
ggplot(proportions, aes(x = CellType, y = Proportion, fill = Condition)) +
  geom_bar(stat = "identity", position = "stack") +
  theme_minimal() +
  # Rotate labels so they don't overlap
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(y = "Fraction of Cells", title = "Proportion of WT vs KO per Identity") +
  scale_y_continuous(labels = scales::percent)
```

Observation: 
Pluripotent Cells are more in KO since they struggle to differentiate and remain indeed undifferentiated.
Arterial EC are way more in WT since they differentiate more than KO (so less pluripotent).

# Next analysis
```{r}


```


